baseURL = "https://sdgmf.github.io/"
title = "Sdgmf 's Blog"
theme = "minimal-bootstrap-hugo-theme"
pygmentsstyle = "monokai"
pygmentscodefences = true
# linenostart=199
# pygmentsOptions = true
# linenos = "table"
# pygmentscodefencesguesssyntax = true
# pygmentsUseClassic=true 

#googleAnalytics="UA-144729654-1"
googleAnalytics="UA-144925501-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  description = "Sdgmf's Blog"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#797D7F"
  navbarLinkColor = "#17202A"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "1600px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-123456789-1"
  cookieConsent = true
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"
	[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
		owner = "sdgmf" # github用户名
		repo = "sdgmf.github.io"    # 仓库地址The repo to store comments
		issueTerm = "pathname"  
		theme = "github-light"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 4