baseURL = "https://sdgmf.github.io/"
title = "Sdgmf 's Blog"
theme = "tachyons"
pygmentsstyle = "monokai"
pygmentscodefences = true
# linenostart=199
# pygmentsOptions = true
# linenos = "table"
# pygmentscodefencesguesssyntax = true
# pygmentsUseClassic=true 
[params]
	[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
		owner = "sdgmf" # github用户名
		repo = "sdgmf.github.io"    # 仓库地址The repo to store comments
		issueTerm = "pathname"  
		theme = "github-light"