baseURL = "https://sdgmf.github.io/"
title = "Sdgmf 's Blog"
theme = "contrast-hugo"
pygmentsstyle = "monokai"
pygmentscodefences = true
# linenostart=199
# pygmentsOptions = true
# linenos = "table"
# pygmentscodefencesguesssyntax = true
# pygmentsUseClassic=true 

#googleAnalytics="UA-144729654-1"
googleAnalytics="UA-144925501-1"


[params]
    brightheader = true
	[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
		owner = "sdgmf" # github用户名
		repo = "sdgmf.github.io"    # 仓库地址The repo to store comments
		issueTerm = "pathname"  
		theme = "github-light"
