baseURL = "https://sdgmf.github.io/"
title = "Sdgmf 's Blog"
theme = "dream-plus"
themesDir = "./themes"		#Don't use this, only for exampleSite
paginate = 4
enableRobotsTXT = false
disqusShortname = "dream-plus"

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2019

	[params.author]
		name = "Sdgmf"
		description = "blog"
		avatar = "/images/avatar.jpeg"
		motto = "Self-discipline gives me freedom"

	[params.features]
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["/css/highlight.css"]

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true
	[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
		owner = "sdgmf" # github用户名
		repo = "sdgmf.github.io"    # 仓库地址The repo to store comments
		issueTerm = "pathname"  
		theme = "github-light"
[social]
	email = "smxe.sdgmf@gmail.com"
	github = "sdgmf"
