baseURL = "https://sdgmf.github.io/"
languageCode = "en-us"
title = "Sdgmf 's Blog"
theme = "ezhil"

# Enable syntax highlighting.
# pygmentsstyle = "vs"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

# Your Google analytics code.
googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "localhost"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Blog"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true
	[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
		owner = "sdgmf" # github用户名
		repo = "sdgmf.github.io"    # 仓库地址The repo to store comments
		issueTerm = "pathname"  
		theme = "github-light"
# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/sdgmf"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Enable tags.
[taxonomies]
   tag = "tags"